// Generated by scripts/build-transcripts.mjs from content/transcripts/. Do not edit by hand.
import type { AudioTrack } from './cooks';

export const transcriptManifest: Record<string, AudioTrack['kind'][]> = {
  "ana-gisela-mora": [
    "biography",
    "recipe"
  ],
  "brigida-cardenas": [
    "biography",
    "recipe"
  ],
  "candelaria-pastora": [
    "biography",
    "recipe"
  ],
  "catalina-herrera": [
    "biography",
    "recipe"
  ],
  "cosmelina-sucre": [
    "biography",
    "recipe"
  ],
  "dilia-fernandez": [
    "biography",
    "recipe"
  ],
  "elisa-padron": [
    "biography",
    "recipe"
  ],
  "esperanza-rivera-guevara": [
    "biography",
    "recipe"
  ],
  "estela-escobar-santeliz": [
    "biography",
    "recipe"
  ],
  "isabel-marin": [
    "biography",
    "recipe"
  ],
  "isolina-flores": [
    "biography",
    "recipe"
  ],
  "josefina-pineda-pina": [
    "biography",
    "recipe"
  ],
  "juana-bautista-marval": [
    "biography",
    "recipe"
  ],
  "julieta-fontainer": [
    "biography",
    "recipe"
  ],
  "karla-herrera-wulff": [
    "biography",
    "recipe"
  ],
  "lolimar-mijares": [
    "biography",
    "recipe"
  ],
  "lucia-torrealba-london": [
    "biography",
    "recipe"
  ],
  "luz-castejon": [
    "biography",
    "recipe"
  ],
  "maria-gabriela-castellanos": [
    "biography",
    "recipe"
  ],
  "maria-morales": [
    "biography",
    "recipe"
  ],
  "maria-munoz": [
    "biography",
    "recipe"
  ],
  "marisol-quiroz": [
    "biography",
    "recipe"
  ],
  "nereida-machado": [
    "biography",
    "recipe"
  ],
  "sonia-prieto": [
    "biography",
    "recipe"
  ],
  "yarenis-rosario": [
    "biography",
    "recipe"
  ]
};

export function hasTranscript(slug: string, kind: AudioTrack['kind']): boolean {
  return transcriptManifest[slug]?.includes(kind) ?? false;
}
