// Generated by scripts/build-transcripts.mjs from content/transcripts/. Do not edit by hand.
import type { AudioTrack } from './cooks';

export const transcriptManifest: Record<string, AudioTrack['kind'][]> = {
  "catalina-herrera": [
    "biography",
    "recipe"
  ],
  "cosmelina-sucre": [
    "biography",
    "recipe"
  ],
  "dilia-fernandez": [
    "biography",
    "recipe"
  ],
  "elisa-padron": [
    "biography",
    "recipe"
  ],
  "esperanza-rivera-guevara": [
    "biography",
    "recipe"
  ],
  "estela-escobar-santeliz": [
    "biography",
    "recipe"
  ],
  "isabel-marin": [
    "biography",
    "recipe"
  ],
  "isolina-flores": [
    "biography",
    "recipe"
  ],
  "josefina-pineda-pina": [
    "biography",
    "recipe"
  ]
};

export function hasTranscript(slug: string, kind: AudioTrack['kind']): boolean {
  return transcriptManifest[slug]?.includes(kind) ?? false;
}
